version: "3.9"
services:
  db:
    image: postgres:15.4-alpine
    container_name: balanz_db
    environment:
      - POSTGRES_USER=balanz
      - POSTGRES_PASSWORD=balanz
      - POSTGRES_DB=balanz
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U balanz -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: -p 5432
